#!/bin/bash
# =============================================================
# deploy.sh — Phase 4: Deploy all 30 projects to Vercel
#
# Each project deploys as an ISOLATED Vercel project,
# linked to the same GitHub repo but scoped to its subfolder.
# The ignoreCommand in each vercel.json ensures only the
# changed project redeploys on future git pushes.
#
# Usage:
#   bash scripts/deploy.sh                             # all 30
#   bash scripts/deploy.sh p1-digital-asset-s1-bento  # one only
#
# .env at root must contain:
#   GEMINI_API_KEY=...
#   VERCEL_TOKEN=...
#   VERCEL_ORG_ID=...
# =============================================================

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECTS_DIR="$ROOT_DIR/projects"
MANIFEST="$ROOT_DIR/manifest.json"
FAILED_LOG="$ROOT_DIR/failed_deploys.txt"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'

echo -e "${BLUE}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   HACKATHON FACTORY — VERCEL DEPLOY          ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════╝${NC}"
echo ""

# ─────────────────────────────────────────────
# Load and validate .env
# ─────────────────────────────────────────────
if [ ! -f "$ROOT_DIR/.env" ]; then
  echo -e "${RED}✗ .env not found at root. Create it with:${NC}"
  echo "  GEMINI_API_KEY=..."
  echo "  VERCEL_TOKEN=..."
  echo "  VERCEL_ORG_ID=..."
  exit 1
fi

set -a; source "$ROOT_DIR/.env"; set +a

[ -z "$VERCEL_TOKEN" ]   && { echo -e "${RED}✗ VERCEL_TOKEN missing in .env${NC}";   exit 1; }
[ -z "$VERCEL_ORG_ID" ]  && { echo -e "${RED}✗ VERCEL_ORG_ID missing in .env${NC}";  exit 1; }
[ -z "$GEMINI_API_KEY" ] && { echo -e "${RED}✗ GEMINI_API_KEY missing in .env${NC}"; exit 1; }

echo -e "${GREEN}✓ VERCEL_TOKEN loaded${NC}"
echo -e "${GREEN}✓ VERCEL_ORG_ID: $VERCEL_ORG_ID${NC}"
echo -e "${GREEN}✓ GEMINI_API_KEY loaded${NC}"
echo ""

# Export so vercel CLI picks them up automatically
export VERCEL_TOKEN
export VERCEL_ORG_ID

# ─────────────────────────────────────────────
# Select projects to deploy
# ─────────────────────────────────────────────
if [ -n "$1" ]; then
  PROJECTS=("$1")
  echo -e "Mode: ${YELLOW}single project → $1${NC}"
else
  PROJECTS=()
  for dir in "$PROJECTS_DIR"/*/; do
    [ -d "$dir" ] && PROJECTS+=("$(basename "$dir")")
  done
  echo -e "Mode: ${YELLOW}all ${#PROJECTS[@]} projects${NC}"
fi

TOTAL=${#PROJECTS[@]}
echo ""

# ─────────────────────────────────────────────
# Load existing manifest (preserve past URLs)
# ─────────────────────────────────────────────
[ -f "$MANIFEST" ] && MANIFEST_CONTENT=$(cat "$MANIFEST") || MANIFEST_CONTENT="{}"

# Clear failed log for this run
> "$FAILED_LOG"
SUCCESS=0
SKIPPED=0
FAILED_COUNT=0
INDEX=0

# ─────────────────────────────────────────────
# Deploy loop
# ─────────────────────────────────────────────
for SLUG in "${PROJECTS[@]}"; do
  INDEX=$((INDEX + 1))
  DIR="$PROJECTS_DIR/$SLUG"

  echo -e "${BLUE}[$INDEX/$TOTAL]${NC} ${YELLOW}▶ $SLUG${NC}"

  # ── Guard: folder must exist ───────────────
  if [ ! -d "$DIR" ]; then
    echo -e "  ${RED}✗ Folder not found — skipping${NC}"
    echo "$SLUG — folder missing" >> "$FAILED_LOG"
    FAILED_COUNT=$((FAILED_COUNT + 1)); echo ""; continue
  fi

  # ── Guard: must be generated by Claude ────
  PAGE="$DIR/app/page.tsx"
  if [ ! -f "$PAGE" ] || grep -q "Awaiting generation" "$PAGE" 2>/dev/null; then
    echo -e "  ${YELLOW}⚠ Not generated yet (placeholder found) — skipping${NC}"
    echo "$SLUG — not generated" >> "$FAILED_LOG"
    SKIPPED=$((SKIPPED + 1)); echo ""; continue
  fi

  # ── Step 1: Add GEMINI_API_KEY to Vercel env ──────────────
  # Runs silently — errors if key already exists, that's fine
  echo -e "  → Setting GEMINI_API_KEY in Vercel..."
  echo "$GEMINI_API_KEY" | vercel env add GEMINI_API_KEY production \
    --token "$VERCEL_TOKEN" \
    --cwd "$DIR" \
    --yes > /dev/null 2>&1 || true

  # ── Step 2: Deploy ─────────────────────────────────────────
  echo -e "  → Deploying..."
  DEPLOY_OUTPUT=$(
    vercel deploy \
      --prod \
      --yes \
      --token "$VERCEL_TOKEN" \
      --cwd "$DIR" \
      2>&1
  )
  EXIT_CODE=$?

  if [ $EXIT_CODE -ne 0 ]; then
    echo -e "  ${RED}✗ Deploy failed:${NC}"
    echo "$DEPLOY_OUTPUT" | tail -5 | sed 's/^/    /'
    echo "$SLUG" >> "$FAILED_LOG"
    FAILED_COUNT=$((FAILED_COUNT + 1)); echo ""; continue
  fi

  # ── Step 3: Extract production URL ────────────────────────
  # vercel deploy --prod prints the URL as the last https:// line
  URL=$(echo "$DEPLOY_OUTPUT" | grep -Eo "https://[a-zA-Z0-9._-]+\.vercel\.app" | tail -1)

  if [ -z "$URL" ]; then
    URL="https://vercel.com/dashboard (check manually)"
  fi

  echo -e "  ${GREEN}✅ Live → $URL${NC}"

  # ── Step 4: Save to manifest ───────────────────────────────
  MANIFEST_CONTENT=$(python3 - <<PYEOF
import json
data = json.loads("""$MANIFEST_CONTENT""")
data["$SLUG"] = "$URL"
print(json.dumps(data, indent=2))
PYEOF
)
  echo "$MANIFEST_CONTENT" > "$MANIFEST"
  SUCCESS=$((SUCCESS + 1))
  echo ""

done

# ─────────────────────────────────────────────
# Final summary
# ─────────────────────────────────────────────
echo -e "${BLUE}╔══════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   DEPLOY SUMMARY                             ║${NC}"
echo -e "${BLUE}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${GREEN}✅ Deployed:  $SUCCESS${NC}"
echo -e "  ${YELLOW}⚠  Skipped:  $SKIPPED (not generated yet)${NC}"
echo -e "  ${RED}✗  Failed:   $FAILED_COUNT${NC}"
echo ""
echo -e "  All URLs → ${GREEN}cat manifest.json${NC}"

if [ $FAILED_COUNT -gt 0 ] || [ $SKIPPED -gt 0 ]; then
  echo ""
  echo -e "  ${YELLOW}Issues logged → failed_deploys.txt${NC}"
  echo -e "  Retry a single project:"
  echo -e "    ${YELLOW}bash scripts/deploy.sh <slug>${NC}"
  echo ""
  if [ -s "$FAILED_LOG" ]; then
    echo -e "  ${RED}Problem list:${NC}"
    cat "$FAILED_LOG" | sed 's/^/    - /'
  fi
fi

echo ""